export enum PlanLabel {
  selectedTabA = 1,
  selectedTabB = 2,
  selectedTabC = 3,
  OutOffice = 'Out Office',
  Remote = 'Remote',
  In_Office = 'In Office',
  Unknown = 'Unknown',
  Booking = 'Booking',
  Available = 'Available',
  Unavailable = 'Unavailable',
  fire_icon_aid = 1,
  fire_icon = 2,
}

export const PlanTextLabel = {
  Currently_there_is_no_desk: 'Currently_there_is_no_desk',
  Currentlythereisnodesk: 'Currently there is no desk',
  No_records: 'No_records',
  Norecords: 'No records',
  In_Office: 'In_Office',
  InOffice: 'In Office',
  Book: 'Book',
  Available: 'Available',
  Partially_available: 'Partially Available',
  Booked: 'Booked',
  Working_remotely: 'Working_remotely',
  Workingremotely: 'Working remotely',
  By_request: 'By_request',
  Byrequest: 'By request',
  Booking: 'Booking',
  Booked_by: 'Booked by me',
  Bookedby: 'Booked by me',
  Out_of_office: 'Out_of_office',
  Outofoffice: 'Out of office',
  Pending_for: 'Pending_for',
  Pendingfor: 'Pending for',
  Unknown: 'Unknown',
  Unavailable: 'Unavailable',
  Description: 'Description',
  Update: 'Update',
  Delete: 'Delete',
  Cancel: 'Cancel',
  Capacity: 'Capacity',
  Locate: 'Locate',
  Participants: 'Participants',
  Dashboard: 'Dashboard',
  Push_Notifications: 'Push_Notifications',
  Floorplan_Management: 'Floorplan_Management',
  User_Management: 'User_Management',
  name: 'name',
  Apply: 'Apply',
  Search: 'Search',
  Filter: 'Filter',
  Today: 'Today',
  View_by: 'View_by',
  Viewby: 'View by',
  Month: 'Month',
  Team: 'Team',
  Day: 'Day',
  Common_Values: 'Common_Values',
  Pending: 'Requested by me',
  Internal_Participants: 'Internal_Participants',
  InternalParticipants: 'Internal Participants',
  External_Participants: 'External_Participants',
  ExternalParticipants: 'External Participants',
  noMatchFound: 'No matching results found',
  subject: 'Subject',
  comments: 'Comments',
  optional: 'optional',
};

export enum AssetStatus {
  AVAILABLE = 1,
  AVAILABLE_BY_REQUEST = 2,
  UN_AVAILABLE = 3,
}

export enum BookingStatus {
  BOOKED = 1,
  PENDING = 4,
}

export const emailRegex = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i;

export const ViewByIds = {
  month: '1',
  team: '2',
  day: '3',
};
