export enum tenantText {
  create = 'create',
  Edit_tenant = 'Edit tenant',
  Create_new_tenant = 'Create new tenant',
}
export const TenantLabelText = {
  Tenant_Settings: 'Tenant Settings',
  Firstname: 'First name',
  First_name: 'First_Name',
  LastName: 'Last name',
  Last_Name: 'Last_Name',
  Create_a_new_tenant: ' Create a new tenant',
  Find: 'Find',
  Save_changes: 'Save changes',
  Active_only: '  Active only',
  Common_Values: 'Common_Values',
  Save: 'Save',
  Cancel: 'Cancel',
  Initial_configuration: 'Initial configuration',
  Plan: 'Plan',
  Server_location: ' Server location',
  Tenant_name: 'Tenant name',
  later_date: ' This cannot be changed at a later date',
  Type_of_login: 'Type of login',
  Web_identity_provider: 'Web identity provider',
  Mobile_identity_provider: 'Mobile identity provider',
  Calendar_integration: 'Calendar integration',
  deleteTenant:
    'Deleting a tenant is only available after the subscription/trial period has ended.',
  Delete_tenant: 'Delete tenant',
  DeleteContent:
    'Are you sure you want to delete this tenant? All data and records will be removed.',
  Max_Workspaces: 'Max no. of Workspaces',
  Max_Rooms: 'Max no. of Rooms',
  Max_Parking: 'Max no. of Parking',
  Max_Users: 'Max no. of Users',
  Invite_the_first_admin: 'Invite the first admin',
  Tenant_admin: 'Tenant admin email',
  Continue: 'Continue',
  Trial: 'Trial',
  Yes: 'Yes',
  No: 'No',
  Trail_start_date: 'Trail start date',
  Trail_end_date: 'Trail end date',
  Subscription_start_date: 'Subscription start date',
  Subscription_end_date: 'Subscription end date',
  Subscription_auto_renew: 'Subscription auto renew',
  SSO_login_audit_enabled: 'SSO login audit enabled',
  Active: 'Active',
  Download_template: 'Download template',
  Upload_data_file: 'Upload data file',
  No_file_uploaded: 'No file uploaded',
  file_validation: 'Set up file validation',
  Out_of_total: 'Out of a total of  ',
  entries_uploaded: ' entries you have uploaded...',
  are_successful: ' are successful',
  While: 'While',
  entries_invalid: ' are entries are invalid',
  entries_system: 'entries already exist in our system',
  re_upload: 'If you wish to make changes and re-upload, click:',
  Return: 'Return',
  further_breakdown: 'Keep scrollin for a further breakdown',
  aresuccessful: ' are successful ',
  reportfile: ' Please click here to download the report file.',
};
