const Canvas = [
  {
    asset_id: 3,
    asset_name: 'Room-001',
    asset_image_path: '/images/meeting_room1.jpg',
    asset_type: 5,
    asset_type_name: 'Desk',
    floorplan_type: 'Workspace',
    asset_color: '#D99797',
    asset_description: 'DGT Room Details',
    asset_capacity: 6,
    asset_amenities: '1,2,3',
    default_start_time: '08:00:00',
    default_end_time: '22:00:00',
    booking_username: 'sharmi',
    booking_email: 'sharmila.manickam@dreamguystech.com',
    user_start_time: '9:00',
    user_end_time: '6:00',
    asset_status: 1,
    my_cordinate: [[{ x: '-10', y: '-5' }]],
    x_cordinate: -10,
    y_cordinate: -5,
    degree: 45,
    width: 40,
    height: 40,
    background_image_path: null,
  },
  {
    asset_id: 2,
    asset_name: 'Desk-002',
    asset_image_path: '/images/square_table.jpg',
    asset_type: 1,
    asset_type_name: 'Tabel',
    floorplan_type: 'Rooms',
    asset_color: '#D99797',
    asset_description: null,
    asset_capacity: null,
    asset_amenities: '3,4,5',
    default_start_time: '00:00:00',
    default_end_time: '00:00:00',
    booking_username: 'sharmi1',
    booking_email: 'test@gmail.com',
    user_start_time: '9:00',
    user_end_time: '6:00',
    asset_status: 1,
    my_cordinate: [[{ x: '-10', y: '-5' }]],
    x_cordinate: -10,
    y_cordinate: -5,
    degree: 45,
    width: 40,
    height: 40,
    background_image_path: null,
  },
  {
    asset_id: 4,
    asset_name: 'Desk-003',
    asset_image_path: '/images/square_table.jpg',
    asset_type: 1,
    asset_type_name: 'Tabel',
    floorplan_type: 'Workspace',
    asset_color: '#006600',
    asset_description: 'Desk Lorem Desc Sample',
    asset_capacity: null,
    asset_amenities: '1,2,3',
    default_start_time: '07:00:00',
    default_end_time: '22:00:00',
    booking_username: null,
    booking_email: null,
    user_start_time: null,
    user_end_time: null,
    asset_status: 1,
    my_cordinate: [[{ x: '-10', y: '-5' }]],
    x_cordinate: 10,
    y_cordinate: 5,
    degree: 45,
    width: 40,
    height: 40,
    background_image_path: null,
  },
];

const amenitiesStatic = [
  {
    amenities_id: '3',
    name: 'Monitor',
    type: 1,
  },
  {
    amenities_id: '4',
    name: 'Keyboard',
    type: 1,
  },
  {
    amenities_id: '5',
    name: 'Mouse',
    type: 1,
  },
  {
    amenities_id: '6',
    name: 'Wifi',
    type: 1,
  },
  {
    amenities_id: '7',
    name: 'Charging Unit',
    type: 1,
  },
  {
    amenities_id: '8',
    name: 'Adjustable Height',
    type: 1,
  },
];

export { amenitiesStatic, Canvas };
