export { default as logo } from '../assets/img/logo.png';
export { default as icon1 } from '../assets/img/icons/login-icon-01.svg';
export { default as icon2 } from '../assets/img/icons/login-icon-02.svg';
export { default as icon3 } from '../assets/img/icons/login-icon-03.svg';
export { default as dropdownAngle } from '../assets/img/icons/dropdown-angle.svg';
export { default as dropdownAngleGrey } from '../assets/img/icons/dropdown-angle-grey.svg';
export { default as upImage } from '../assets/img/icons/up.svg';
export { default as plusicon } from '../assets/img/icons/plus-icon.svg';
export { default as Search } from '../assets/img/icons/search.svg';
export { default as EyeIcon } from '../assets/img/icons/eye-icon.svg';
export { default as calendar } from '../assets/img/icons/calendar.svg';
export { default as calendar1 } from '../assets/img/icons/calander1.svg';
export { default as Notification } from '../assets/img/icons/notification.svg';
export { default as member } from '../assets/img/icons/member.svg';
export { default as User } from '../assets/img/icons/user.svg';
export { default as logo_svg } from '../assets/img/logo.svg';
export { default as hybrid_logo } from '../assets/img/icons/Bottom_Logo.png';
export { default as alert_icon } from '../assets/img/icons/alert-icon.svg';
export { default as notification_chair } from '../assets/img/icons/notification-chair.svg';
export { default as plus2 } from '../assets/img/icons/plus2.svg';
export { default as SidebarProfile } from '../assets/img/profiles/sideber-profile.jpg';
export { default as DashboardIcon } from '../assets/img/icons/menu-01.svg';
export { default as setting_icon } from '../assets/img/icons/settings-icon.svg';
export { default as history_icon } from '../assets/img/icons/tab-icon2.svg';
export { default as logout_icon } from '../assets/img/icons/logout-icon.svg';
export { default as LocateIcon } from '../assets/img/icons/menu-02.svg';
export { default as BookIcon } from '../assets/img/icons/menu-03.svg';
export { default as TeamIcon } from '../assets/img/icons/menu-04.svg';
export { default as WellbeingIcon } from '../assets/img/icons/menu-05.svg';
export { default as ReportsIcon } from '../assets/img/icons/menu-06.svg';
export { default as CompanyLogo } from '../assets/img/company-logo.png';
export { default as TimeleftIcon } from '../assets/img/icons/time-left.svg';
export { default as TimeRightIcon } from '../assets/img/icons/time-right.svg';
export { default as ChairIcon } from '../assets/img/icons/chair.svg';
export { default as locatIcon } from '../assets/img/icons/locat-icon-01.svg';
export { default as tableicon1 } from '../assets/img/icons/table-icon-01.svg';
export { default as tableicon2 } from '../assets/img/icons/table-icon-02.svg';
export { default as icon_01 } from '../assets/img/icons/icon-01.svg';
export { default as flooricon } from '../assets/img/icons/floor-icon.svg';
export { default as contact_icon_01 } from '../assets/img/icons/contact-icon-01.svg';
export { default as contact_icon_02 } from '../assets/img/icons/contact-icon-02.svg';
export { default as contact_icon_03 } from '../assets/img/icons/contact-icon-03.svg';
export { default as icon_02 } from '../assets/img/icons/icon-02.svg';
export { default as RoomIcon } from '../assets/img/icons/check-icon-01.svg';
export { default as ParkingIcon } from '../assets/img/icons/check-icon-02.svg';
export { default as WorkspacesIcon } from '../assets/img/icons/check-icon-03.svg';
export { default as Desk1 } from '../assets/img/icons/chair.svg';
export { default as EditIcon } from '../assets/img/icons/edit.svg';
export { default as dropdown_angel } from '../assets/img/icons/dropdown-angle.svg';
export { default as LeftAngle } from '../assets/img/icons/left-angle.svg';
export { default as Avatar1 } from '../assets/img/profiles/avatar-01.jpg';
export { default as Avatar2 } from '../assets/img/profiles/avatar-02.jpg';
export { default as Avatar3 } from '../assets/img/profiles/avatar-03.jpg';
export { default as Avatar4 } from '../assets/img/profiles/avatar-04.jpg';
export { default as Avatar5 } from '../assets/img/profiles/avatar-05.jpg';
export { default as Avatar6 } from '../assets/img/profiles/avatar-06.jpg';
export { default as Avatar10 } from '../assets/img/profiles/avatar-10.jpg';
export { default as Avatar11 } from '../assets/img/profiles/avatar-11.jpg';
export { default as Avatar12 } from '../assets/img/profiles/avatar-12.jpg';
export { default as Avatar8 } from '../assets/img/profiles/avatar-08.jpg';
export { default as Avatar14 } from '../assets/img/profiles/avatar-14.jpg';
export { default as Avatar15 } from '../assets/img/profiles/avatar-15.jpg';
export { default as Avatar16 } from '../assets/img/profiles/avatar-16.jpg';
export { default as Avatar17 } from '../assets/img/profiles/avatar-17.jpg';
export { default as Avatar18 } from '../assets/img/profiles/avatar-18.jpg';
export { default as HDPlusLogo } from '../assets/img/HH-icon.svg';
export { default as OktaIcon } from '../assets/img/icons/login-icon-02.svg';
export { default as WindowsIcon } from '../assets/img/icons/login-icon-01.svg';
export { default as RefreshIcon } from '../assets/img/icons/refresh-icon.svg';
export { default as GoogleIcon } from '../assets/img/icons/google-icon.svg';
export { default as floorplan } from '../assets/img/floorplan.jpg';
export { default as filter_icon } from '../assets/img/icons/filter.svg';
export { default as filters } from '../assets/img/icons/filters.svg';
export { default as location } from '../assets/img/icons/location.svg';
export { default as topdown } from '../assets/img/icons/top-down.svg';
export { default as fire } from '../assets/img/icons/fire.svg';
export { default as plus } from '../assets/img/icons/plus.svg';
export { default as locations } from '../assets/img/icons/locations.svg';
export { default as team_icon } from '../assets/img/icons/team-icon.svg';
export { default as google_icon } from '../assets/img/icons/google-icon.svg';
export { default as zoom_icon } from '../assets/img/icons/zoom-icon.svg';
export { default as zoom_minus_icon } from '../assets/img/icons/zoom-minus-icon.svg';
export { default as zoom_plus_icon } from '../assets/img/icons/zoom-plus-icon.svg';
export { default as refresh_icon } from '../assets/img/icons/refresh-icon.svg';
export { default as book_1 } from '../assets/img/icons/book-01.svg';
export { default as book_2 } from '../assets/img/icons/book-02.svg';
export { default as book_3 } from '../assets/img/icons/book-03.svg';
export { default as book_4 } from '../assets/img/icons/book-04.svg';
export { default as book_5 } from '../assets/img/icons/book-05.svg';
export { default as monthIcon } from '../assets/img/icons/month-icon.svg';
export { default as dayIcon } from '../assets/img/icons/day-icon.svg';
export { default as teamIcon } from '../assets/img/icons/teams-icon.svg';
export { default as bookCalendarIcon } from '../assets/img/icons/book-calendar-icon.svg';
export { default as bookLocation } from '../assets/img/icons/book-location.svg';
export { default as bookingNameIcon } from '../assets/img/icons/booking-name-icon.svg';
export { default as bookingNameIconTwo } from '../assets/img/icons/booking-name-2.svg';
export { default as partialIcon } from '../assets/img/icons/partially-1.svg';
export { default as bookingWhiteIcon } from '../assets/img/icons/book-white-icon.svg';
export { default as booking_icon } from '../assets/img/booking-img.jpg';
export { default as room_icon } from '../assets/img/icons/room.svg';
export { default as workspace1 } from '../assets/img/icons/workspace1.svg';
export { default as workspace2 } from '../assets/img/icons/workspace2.svg';
export { default as workspace3 } from '../assets/img/icons/workspace3.svg';
export { default as workspace4 } from '../assets/img/icons/workspace4.svg';
export { default as workspace5 } from '../assets/img/icons/workspace5.svg';
export { default as undo_icon_disabled } from '../assets/img/icons/undo-icon-disabled.svg';
export { default as inOffice } from '../assets/img/icons/inOffice.png';
export { default as outOffice } from '../assets/img/icons/outOffice.svg';
export { default as workingRemotely } from '../assets/img/icons/workingRemotely.png';

export { default as desk } from '../assets/img/icons/desk.svg';
export { default as locations_2 } from '../assets/img/icons/locations-2.svg';
export { default as room } from '../assets/img/icons/room.svg';
export { default as parking1 } from '../assets/img/icons/parking1.svg';
export { default as parkingDesk } from '../assets/img/icons/parking-desk.svg';
export { default as parkingBooked } from '../assets/img/icons/parking-booked.svg';
export { default as parkingBookedme } from '../assets/img/icons/parking-bookedme.svg';
export { default as parkingRequest } from '../assets/img/icons/parking-request.svg';
export { default as parkingAvail } from '../assets/img/icons/parking-avail.svg';
export { default as parkingUnavail } from '../assets/img/icons/parking-unavail.svg';
export { default as parkingDeskSelected } from '../assets/img/icons/parking-desk-selected.svg';

export { default as parkingAvailFilter } from '../assets/img/icons/parking-filtered/parking-avail.svg';
export { default as parkingBookedFilter } from '../assets/img/icons/parking-filtered/parking-booked.svg';
export { default as parkingBookedmeFilter } from '../assets/img/icons/parking-filtered/parking-bookedme.svg';
export { default as parkingRequestFilter } from '../assets/img/icons/parking-filtered/parking-request.svg';

export { default as floor_01 } from '../assets/img/icons/floor-01.svg';
export { default as floor_img } from '../assets/img/floor-img.jpg';
export { default as text_icon } from '../assets/img/icons/text-icon.svg';
export { default as bold_icon } from '../assets/img/icons/bold-icon.svg';
export { default as italic_icon } from '../assets/img/icons/italic-icon.svg';
export { default as underline_icon } from '../assets/img/icons/underline-icon.svg';
export { default as text_color_icon } from '../assets/img/icons/text-color-icon.svg';
export { default as pan_icon } from '../assets/img/icons/pan-icon.svg';
export { default as zoom_img } from '../assets/img/icons/zoom-img.svg';
export { default as select_icon } from '../assets/img/icons/select-icon.svg';
export { default as drag_icon } from '../assets/img/icons/drag-icon.svg';
export { default as undo_icon } from '../assets/img/icons/undo-icon.svg';
export { default as copy_icon } from '../assets/img/icons/copy-icon.svg';
export { default as paste_icon } from '../assets/img/icons/paste-icon.svg';
export { default as redo_icon } from '../assets/img/icons/redo-icon.svg';
export { default as redo_icon_disabled } from '../assets/img/icons/redo-icon-disabled.svg';
export { default as snap_icon } from '../assets/img/icons/snap-icon.svg';
export { default as import_icon } from '../assets/img/icons/import-icon.svg';
export { default as hide_icon } from '../assets/img/icons/hide-icon.svg';
export { default as unlock_icon } from '../assets/img/icons/unlock-icon.svg';
export { default as lock_icon } from '../assets/img/icons/lock-icon.svg';
export { default as vertical_icon } from '../assets/img/icons/vertical-icon.svg';
export { default as distribute_vertical_icon } from '../assets/img/icons/distribute-vertical-icon.svg';
export { default as horizontal_icon } from '../assets/img/icons/horizontal-icon.svg';
export { default as distribute_horizontal_icon } from '../assets/img/icons/distribute-horizontal-icon.svg';
export { default as floor_02 } from '../assets/img/icons/floor-02.svg';
export { default as floor_03 } from '../assets/img/icons/floor-03.svg';
export { default as floor_04 } from '../assets/img/icons/floor-04.svg';
export { default as remove_icon } from '../assets/img/icons/remove-icon.svg';
export { default as desk_02 } from '../assets/img/icons/desk-02.svg';
export { default as desk_03 } from '../assets/img/icons/desk-03.svg';
export { default as desk_04 } from '../assets/img/icons/desk-04.svg';
export { default as desk_05 } from '../assets/img/icons/desk-05.svg';
export { default as parking } from '../assets/img/icons/parking.svg';
export { default as desk_01 } from '../assets/img/icons/desk-01.svg';
export { default as desk_bookedme } from '../assets/img/icons/desk-bookedme.svg';
export { default as desk_unavail } from '../assets/img/icons/desk-unavail.svg';
export { default as desk_request } from '../assets/img/icons/desk-request.svg';
export { default as workspace_link_icon } from '../assets/img/icons/workspace-link-icon.svg';

export { default as desk_bookedme_filter } from '../assets/img/icons/desk-filtered/desk-bookedme.svg';
export { default as desk_booked_filter } from '../assets/img/icons/desk-filtered/desk-booked.svg';
export { default as desk_request_filter } from '../assets/img/icons/desk-filtered/desk-request.svg';
export { default as desk_avail_filter } from '../assets/img/icons/desk-filtered/desk-avail.svg';

export { default as regular_c } from '../assets/img/icons/regular_c.svg';
export { default as regular_l } from '../assets/img/icons/regular_l.svg';
export { default as regular_c_select } from '../assets/img/icons/regular_c_select.svg';
export { default as regular_l_select } from '../assets/img/icons/regular_l_select.svg';
export { default as regular_c_booked } from '../assets/img/icons/regular_c_booked.svg';
export { default as regular_l_booked } from '../assets/img/icons/regular_l_booked.svg';
export { default as regular_c_bookedme } from '../assets/img/icons/regular_c_bookedme.svg';
export { default as regular_l_bookedme } from '../assets/img/icons/regular_l_bookedme.svg';
export { default as regular_c_unavail } from '../assets/img/icons/regular_c_unavail.svg';
export { default as regular_l_unavail } from '../assets/img/icons/regular_l_unavail.svg';
export { default as regular_c_avail } from '../assets/img/icons/regular_c_avail.svg';
export { default as regular_l_avail } from '../assets/img/icons/regular_l_avail.svg';
export { default as regular_c_request } from '../assets/img/icons/regular_c_request.svg';
export { default as regular_l_request } from '../assets/img/icons/regular_l_request.svg';

export { default as regularC_booked_filter } from '../assets/img/icons/regular-c-filtered/regularC-booked.svg';
export { default as regularC_bookedme_filter } from '../assets/img/icons/regular-c-filtered/regularC-bookedme.svg';
export { default as regularC_avail_filter } from '../assets/img/icons/regular-c-filtered/regularC-avail.svg';
export { default as regularC_request_filter } from '../assets/img/icons/regular-c-filtered/regularC-request.svg';

export { default as regularL_booked_filter } from '../assets/img/icons/regular-l-filtered/regularL-booked.svg';
export { default as regularL_bookedme_filter } from '../assets/img/icons/regular-l-filtered/regularL-bookedme.svg';
export { default as regularL_avail_filter } from '../assets/img/icons/regular-l-filtered/regularL-avail.svg';
export { default as regularL_request_filter } from '../assets/img/icons/regular-l-filtered/regularL-request.svg';

export { default as wall_01 } from '../assets/img/icons/wall-01.svg';
export { default as wall_02 } from '../assets/img/icons/wall-02.svg';
export { default as wall_03 } from '../assets/img/icons/wall-03.svg';
export { default as wall_04 } from '../assets/img/icons/wall-04.svg';
export { default as wall_05 } from '../assets/img/icons/wall-05.svg';
export { default as building_link_icon } from '../assets/img/icons/building-link-icon.svg';
export { default as stairs } from '../assets/img/icons/stairs.svg';
export { default as lift } from '../assets/img/icons/lift.svg';
export { default as onewayroadL } from '../assets/img/icons/onewayroadL.svg';
export { default as onewayroadR } from '../assets/img/icons/onewayroadR.svg';
export { default as twowayroad } from '../assets/img/icons/twowayroad.svg';
export { default as twowayroad90 } from '../assets/img/icons/twowayroad90.svg';

export { default as doorway } from '../assets/img/icons/doorway.svg';
export { default as window } from '../assets/img/icons/window.svg';
export { default as eye_slash_light } from '../assets/img/icons/eye-slash-light.svg';
export { default as edit_icon_light } from '../assets/img/icons/edit-icon-light.svg';
export { default as edit_icon_dark } from '../assets/img/icons/edit-icon-dark.svg';
export { default as eye_slash_dark } from '../assets/img/icons/eye-slash-dark.svg';
export { default as dropdown_angle } from '../assets/img/icons/dropdown-angle.svg';

export { default as favicon } from '../assets/img/favicon.png';
export { default as inactive } from '../assets/img/icons/inactive-arrow.svg';
export { default as alignment_01 } from '../assets/img/icons/alignment-01.svg';
export { default as alignment_02 } from '../assets/img/icons/alignment-02.svg';
export { default as alignment_03 } from '../assets/img/icons/alignment-03.svg';
export { default as alignment_04 } from '../assets/img/icons/alignment-04.svg';
export { default as lshapewall } from '../assets/img/shapes/lshapewall.svg';
export { default as cshapewall } from '../assets/img/shapes/cshapewall.svg';
export { default as singledesk } from '../assets/img/shapes/singledesk.svg';
export { default as singledesk_select } from '../assets/img/shapes/singledesk_select.svg';
export { default as shape2 } from '../assets/img/shapes/shape2.svg';
export { default as shape2_booked } from '../assets/img/shapes/shape2-booked.svg';
export { default as shape2_bookedme } from '../assets/img/shapes/shape2-bookedme.svg';
export { default as shape2_request } from '../assets/img/shapes/shape2-request.svg';
export { default as shape2_unavail } from '../assets/img/shapes/shape2-unavail.svg';
export { default as shape2_avail } from '../assets/img/shapes/shape2-avail.svg';

export { default as shape2_select } from '../assets/img/shapes/shape2_select.svg';
export { default as shape3 } from '../assets/img/shapes/shape3.svg';
export { default as shape3_booked } from '../assets/img/shapes/shape3-booked.svg';
export { default as shape3_bookedme } from '../assets/img/shapes/shape3-bookedme.svg';
export { default as shape3_request } from '../assets/img/shapes/shape3-request.svg';
export { default as shape3_unavail } from '../assets/img/shapes/shape3-unavail.svg';
export { default as shape3_avail } from '../assets/img/shapes/shape3-avail.svg';
export { default as shape3_select } from '../assets/img/shapes/shape3_select.svg';
export { default as shape4 } from '../assets/img/shapes/shape4.svg';
export { default as shape4_select } from '../assets/img/shapes/shape4_select.svg';
export { default as shape5 } from '../assets/img/new-canvas/shape5.svg';
export { default as shape5_booked } from '../assets/img/shapes/shape5-booked.svg';
export { default as shape5_bookedme } from '../assets/img/shapes/shape5-bookedme.svg';
export { default as shape5_avail } from '../assets/img/shapes/shape5-avail.svg';
export { default as shape5_select } from '../assets/img/shapes/shape5_select.svg';

export { default as shape3_booked_filter } from '../assets/img/shapes/shape3-filtered/shape3-booked.svg';
export { default as shape3_bookedme_filter } from '../assets/img/shapes/shape3-filtered/shape3-bookedme.svg';
export { default as shape3_request_filter } from '../assets/img/shapes/shape3-filtered/shape3-request.svg';
export { default as shape3_avail_filter } from '../assets/img/shapes/shape3-filtered/shape3-avail.svg';

export { default as shape2_booked_filter } from '../assets/img/shapes/shape2-filtered/shape2-booked.svg';
export { default as shape2_bookedme_filter } from '../assets/img/shapes/shape2-filtered/shape2-bookedme.svg';
export { default as shape2_request_filter } from '../assets/img/shapes/shape2-filtered/shape2-request.svg';
export { default as shape2_avail_filter } from '../assets/img/shapes/shape2-filtered/shape2-avail.svg';

export { default as cshapewall_img } from '../assets/img/icons/wall-02.svg';
export { default as lshapewall_img } from '../assets/img/icons/wall-03.svg';
export { default as wall_img } from '../assets/img/icons/wall-04.svg';

export { default as cshapewall_img_select } from '../assets/img/icons/wall-02-select.svg';
export { default as lshapewall_img_select } from '../assets/img/icons/wall-03-select.svg';
export { default as wall_img_select } from '../assets/img/icons/wall-04-select.svg';

export { default as roomDesk } from '../assets/img/shapes/room.svg';
export { default as room_booked } from '../assets/img/shapes/room-booked.svg';
export { default as room_bookedme } from '../assets/img/shapes/room-bookedme.svg';
export { default as room_request } from '../assets/img/shapes/room-request.svg';
export { default as room_unavail } from '../assets/img/shapes/room-unavail.svg';
export { default as room_avail } from '../assets/img/shapes/room-avail.svg';
export { default as room_select_img } from '../assets/img/shapes/room-select-img.svg';
export { default as square_room } from '../assets/img/shapes/square-room.svg';

export { default as UserIcon } from '../assets/img/icons/user_new.svg';
export { default as room_booked_filter } from '../assets/img/shapes/room-filtered/room-booked.svg';
export { default as room_bookedme_filter } from '../assets/img/shapes/room-filtered/room-bookedme.svg';
export { default as room_request_filter } from '../assets/img/shapes/room-filtered/room-request.svg';
export { default as room_avail_filter } from '../assets/img/shapes/room-filtered/room-avail.svg';

export { default as room_xxs_avail_filter } from '../assets/img/shapes/room-filtered/room-xxs-avail.svg';
export { default as room_xxs_booked_filter } from '../assets/img/shapes/room-filtered/room-xxs-booked.svg';
export { default as room_xxs_bookedme_filter } from '../assets/img/shapes/room-filtered/room-xxs-bookedme.svg';
export { default as room_xxs_req_filter } from '../assets/img/shapes/room-filtered/room-xxs-req.svg';

export { default as room_xs_avail_filter } from '../assets/img/shapes/room-filtered/room-xs-avail.svg';
export { default as room_xs_booked_filter } from '../assets/img/shapes/room-filtered/room-xs-booked.svg';
export { default as room_xs_bookedme_filter } from '../assets/img/shapes/room-filtered/room-xs-bookedme.svg';
export { default as room_xs_req_filter } from '../assets/img/shapes/room-filtered/room-xs-req.svg';

export { default as room_m_avail_filter } from '../assets/img/shapes/room-filtered/room-m-avail.svg';
export { default as room_m_booked_filter } from '../assets/img/shapes/room-filtered/room-m-booked.svg';
export { default as room_m_bookedme_filter } from '../assets/img/shapes/room-filtered/room-m-bookedme.svg';
export { default as room_m_req_filter } from '../assets/img/shapes/room-filtered/room-m-req.svg';

export { default as room_l_avail_filter } from '../assets/img/shapes/room-filtered/room-l-avail.svg';
export { default as room_l_booked_filter } from '../assets/img/shapes/room-filtered/room-l-booked.svg';
export { default as room_l_bookedme_filter } from '../assets/img/shapes/room-filtered/room-l-bookedme.svg';
export { default as room_l_req_filter } from '../assets/img/shapes/room-filtered/room-l-req.svg';

export { default as room_xl_avail_filter } from '../assets/img/shapes/room-filtered/room-xl-avail.svg';
export { default as room_xl_booked_filter } from '../assets/img/shapes/room-filtered/room-xl-booked.svg';
export { default as room_xl_bookedme_filter } from '../assets/img/shapes/room-filtered/room-xl-bookedme.svg';
export { default as room_xl_req_filter } from '../assets/img/shapes/room-filtered/room-xl-req.svg';

export { default as singledesk_cursor } from '../assets/img/dragicons/SingleDesk-cursor.svg';
export { default as text_cursor } from '../assets/img/dragicons/Text-cursor.svg';
export { default as square_cursor } from '../assets/img/dragicons/Square-cursor.svg';
export { default as closeIconWhiteColor } from '../assets/img/icons/book-xmark.svg';
export { default as notificationWithoutMark } from '../assets/img/icons/notification-remove-red-mark.svg';
export { default as tableDownIcon } from '../assets/img/icons/table-down-icon.svg';
export { default as teamHome } from '../assets/img/icons/team-home.svg';
export { default as teamOutOffice } from '../assets/img/icons/team-out-office.svg';
export { default as teamOffice } from '../assets/img/icons/team-office.svg';

export { default as newDateIcon } from '../assets/img/icons/new-date-icon.svg';
export { default as calendarGrey } from '../assets/img/icons/calendar-grey.svg';

export { default as schedule_01 } from '../assets/img/icons/schedule-01.svg';
export { default as schedule_02 } from '../assets/img/icons/schedule-02.svg';
export { default as schedule_03 } from '../assets/img/icons/schedule-03.svg';
export { default as Vector } from '../assets/img/icons/Vector.svg';

export { default as create_plus } from '../assets/img/icons/create-plus.svg';
export { default as Chair_icon } from '../assets/img/icons/chair-icon.svg';
export { default as upload_chair_icon } from '../assets/img/icons/upload-chair-icon.svg';
export { default as tag_plus } from '../assets/img/icons/tag-plus.svg';
export { default as return_icon1 } from '../assets/img/icons/return-icon1.svg';
export { default as return_icon2 } from '../assets/img/icons/return-icon2.svg';
export { default as return_icon3 } from '../assets/img/icons/return-icon3.svg';
export { default as fire_icon } from '../assets/img/icons/fire-icon.svg';
export { default as firstaid_icon } from '../assets/img/icons/firstaid-icon.svg';
export { default as send_icon } from '../assets/img/icons/send-icon.svg';
export { default as upload_plus_icon } from '../assets/img/icons/upload-plus-icon.svg';
export { default as image_preview } from '../assets/img/icons/image_preview.png';
export { default as Pdf } from '../assets/img/icons/pdf.svg';
export { default as carbon_security } from '../assets/img/icons/carbon_security.svg';
export { default as time_upicon } from '../assets/img/icons/up-arrow.svg';
export { default as time_downicon } from '../assets/img/icons/down-arrow.svg';
export { default as setting_asset } from '../assets/img/icons/asset-setting-icon.svg';
export { default as permision_asset } from '../assets/img/icons/permision-icon.svg';
export { default as menu_07 } from '../assets/img/icons/menu-07.svg';
export { default as menu_08 } from '../assets/img/icons/menu-08.svg';
export { default as menu_09 } from '../assets/img/icons/menu-09.svg';
export { default as status_icon } from '../assets/img/icons/status-icon.svg';
export { default as day_icon1 } from '../assets/img/icons/day-icon1.svg';
export { default as day_icon2 } from '../assets/img/icons/day-icon2.svg';
export { default as day_icon3 } from '../assets/img/icons/day-icon3.svg';
export { default as day_icon4 } from '../assets/img/icons/day-icon4.svg';
export { default as day_icon5 } from '../assets/img/icons/day-icon5.svg';
export { default as calend_icon1 } from '../assets/img/icons/calend-icon1.svg';
export { default as calend_icon2 } from '../assets/img/icons/calend-icon2.svg';
export { default as in_office } from '../assets/img/icons/in-office.svg';
export { default as out_office } from '../assets/img/icons/out-office.svg';
export { default as remote_home } from '../assets/img/icons/remote-home.svg';
export { default as out_of_icon } from '../assets/img/icons/out-of-icon.svg';
export { default as sickness } from '../assets/img/icons/sickness-icon.svg';
export { default as holiday } from '../assets/img/icons/holiday-icon.svg';
export { default as other_icon } from '../assets/img/icons/other-icon.svg';

export { default as Trial_icon } from '../assets/img/tiral-icon.png';
export { default as ReCaptcha } from '../assets/img/re-captcha.png';

export { default as Floorbox_1 } from '../assets/img/icons/quickbook/floor-box1.svg';
export { default as Floorbox_2 } from '../assets/img/icons/quickbook/floor-box2.svg';
export { default as Floorbox_3 } from '../assets/img/icons/quickbook/floor-box3.svg';
export { default as Shard } from '../assets/img/icons/quickbook/shard-icon.svg';
export { default as global } from '../assets/img/icons/quickbook/globe-icon.svg';
export { default as region } from '../assets/img/icons/quickbook/region-icon.svg';
export { default as state } from '../assets/img/icons/quickbook/state-icon.svg';
export { default as country } from '../assets/img/icons/quickbook/country-icon.svg';
export { default as city } from '../assets/img/icons/quickbook/city-icon.svg';
export { default as suburb } from '../assets/img/icons/quickbook/suburb-icon.svg';
export { default as street } from '../assets/img/icons/quickbook/street-icon.svg';

// new-canvas-img
export { default as new_room1 } from '../assets/img/new-canvas/new-room-1.svg';
export { default as new_room2 } from '../assets/img/new-canvas/new-room-2.svg';
export { default as new_room3 } from '../assets/img/new-canvas/new-room-3.svg';
export { default as new_room4 } from '../assets/img/new-canvas/new-room-4.svg';
export { default as new_room5 } from '../assets/img/new-canvas/new-room-5.svg';
export { default as new_room6 } from '../assets/img/new-canvas/new-room-6.svg';

export { default as new_room1_white } from '../assets/img/new-canvas/new-room-1_white.svg';
export { default as new_room2_white } from '../assets/img/new-canvas/new-room-2_white.svg';
export { default as new_room3_white } from '../assets/img/new-canvas/new-room-3_white.svg';
export { default as new_room4_white } from '../assets/img/new-canvas/new-room-4_white.svg';
export { default as new_room5_white } from '../assets/img/new-canvas/new-room-5_white.svg';
export { default as new_room6_white } from '../assets/img/new-canvas/new-room-6_white.svg';

export { default as new_room1_select } from '../assets/img/new-canvas/new-room-1_select.svg';
export { default as new_room2_select } from '../assets/img/new-canvas/new-room-2_select.svg';
export { default as new_room3_select } from '../assets/img/new-canvas/new-room-3_select.svg';
export { default as new_room4_select } from '../assets/img/new-canvas/new-room-4_select.svg';
export { default as new_room5_select } from '../assets/img/new-canvas/new-room-5_select.svg';
export { default as new_room6_select } from '../assets/img/new-canvas/new-room-6_select.svg';

export { default as room_xxs_avail } from '../assets/img/new-canvas/room-xxs-avail.svg';
export { default as room_xxs_booked } from '../assets/img/new-canvas/room-xxs-booked.svg';
export { default as room_xxs_bookedme } from '../assets/img/new-canvas/room-xxs-bookedme.svg';
export { default as room_xxs_req } from '../assets/img/new-canvas/room-xxs-req.svg';
export { default as room_xxs_unavail } from '../assets/img/new-canvas/room-xxs-unavail.svg';

export { default as room_xs_avail } from '../assets/img/new-canvas/room-xs-avail.svg';
export { default as room_xs_booked } from '../assets/img/new-canvas/room-xs-booked.svg';
export { default as room_xs_bookedme } from '../assets/img/new-canvas/room-xs-bookedme.svg';
export { default as room_xs_req } from '../assets/img/new-canvas/room-xs-req.svg';
export { default as room_xs_unavail } from '../assets/img/new-canvas/room-xs-unavail.svg';

export { default as room_m_avail } from '../assets/img/new-canvas/room-m-avail.svg';
export { default as room_m_booked } from '../assets/img/new-canvas/room-m-booked.svg';
export { default as room_m_bookedme } from '../assets/img/new-canvas/room-m-bookedme.svg';
export { default as room_m_req } from '../assets/img/new-canvas/room-m-req.svg';
export { default as room_m_unavail } from '../assets/img/new-canvas/room-m-unavail.svg';

export { default as room_l_avail } from '../assets/img/new-canvas/room-l-avail.svg';
export { default as room_l_booked } from '../assets/img/new-canvas/room-l-booked.svg';
export { default as room_l_bookedme } from '../assets/img/new-canvas/room-l-bookedme.svg';
export { default as room_l_req } from '../assets/img/new-canvas/room-l-req.svg';
export { default as room_l_unavail } from '../assets/img/new-canvas/room-l-unavail.svg';

export { default as room_xl_avail } from '../assets/img/new-canvas/room-xl-avail.svg';
export { default as room_xl_booked } from '../assets/img/new-canvas/room-xl-booked.svg';
export { default as room_xl_bookedme } from '../assets/img/new-canvas/room-xl-bookedme.svg';
export { default as room_xl_req } from '../assets/img/new-canvas/room-xl-req.svg';
export { default as room_xl_unavail } from '../assets/img/new-canvas/room-xl-unavail.svg';

export { default as new_parking1 } from '../assets/img/new-canvas/parking-1.svg';
export { default as new_parking2 } from '../assets/img/new-canvas/parking-2.svg';
export { default as new_parking3 } from '../assets/img/new-canvas/parking-3.svg';
export { default as new_parking4 } from '../assets/img/new-canvas/parking-4.svg';
export { default as new_parking5 } from '../assets/img/new-canvas/parking-5.svg';
export { default as new_parking6 } from '../assets/img/new-canvas/parking-6.svg';
export { default as new_parking7 } from '../assets/img/new-canvas/parking-7.svg';
export { default as new_parking8 } from '../assets/img/new-canvas/parking-8.svg';

export { default as new_parking_select } from '../assets/img/new-canvas/parking-1_select.svg';
export { default as new_singledesk_select } from '../assets/img/new-canvas/new-singledesk_select.svg';
export { default as new_lshapedesk_select } from '../assets/img/new-canvas/new-shape5_select.svg';
export { default as new_parking_white } from '../assets/img/new-canvas/parking-1_white.svg';

export { default as new_desk1 } from '../assets/img/new-canvas/desk-1.svg';
export { default as new_desk2 } from '../assets/img/new-canvas/desk-2.svg';
export { default as new_desk3 } from '../assets/img/new-canvas/desk-3.svg';
export { default as new_desk4 } from '../assets/img/new-canvas/desk-4.svg';
export { default as new_desk5 } from '../assets/img/new-canvas/desk-5.svg';
export { default as new_desk6 } from '../assets/img/new-canvas/desk-6.svg';
export { default as new_desk7 } from '../assets/img/new-canvas/desk-7.svg';
export { default as new_desk8 } from '../assets/img/new-canvas/desk-8.svg';
export { default as directory_icon } from '../assets/img/icons/directory-icon.svg';

export { default as singledesk_withoutText } from '../assets/img/shapes/singledesk_withoutText.svg';
export { default as shape5_withoutText } from '../assets/img/shapes/shape5_withoutText.svg';

// HR Module
export { default as HRIconSmall } from '../assets/img/icons/hrIcon1.svg';
export { default as HRIcon } from '../assets/img/icons/menu-07.svg';
export { default as profileImg } from '../assets/img/profiles/profile-view.jpg';
export { default as hrIcon1 } from '../assets/img/icons/hr-icon1.svg';
export { default as hrIcon2 } from '../assets/img/icons/hr-icon2.svg';
export { default as hrIcon3 } from '../assets/img/icons/hr-icon3.svg';
export { default as hrIcon4 } from '../assets/img/icons/hr-icon4.svg';
export { default as hrIcon5 } from '../assets/img/icons/hr-icon5.svg';
export { default as hrIcon6 } from '../assets/img/icons/hr-icon6.svg';
export { default as hrIcon7 } from '../assets/img/icons/hr-icon7.svg';
export { default as hrIcon8 } from '../assets/img/icons/hr-icon8.svg';
export { default as hrIcon9 } from '../assets/img/icons/hr-icon9.svg';
export { default as hrIcon10 } from '../assets/img/icons/hr-icon10.svg';
export { default as employeeIcon } from '../assets/img/icons/employee-icon.svg';
export { default as employeeAddress } from '../assets/img/icons/employee-address.svg';
export { default as emergencyIcon } from '../assets/img/icons/emergency-icon.svg';
export { default as pencilIcon } from '../assets/img/icons/pencil-icon.svg';
export { default as educationIcon } from '../assets/img/icons/education-icon.svg';
export { default as certificateIcon } from '../assets/img/icons/certificate-icon.svg';
export { default as identificationIcon } from '../assets/img/icons/identification-icon.svg';
export { default as visaIcon } from '../assets/img/icons/visa-icon.svg';
export { default as vaccinationIcon } from '../assets/img/icons/vaccination-icon.svg';
export { default as tabIcon1 } from '../assets/img/icons/tab-icon1.svg';
export { default as tabIcon2 } from '../assets/img/icons/tab-icon2.svg';
export { default as tabIcon3 } from '../assets/img/icons/tab-icon3.svg';
export { default as hrCalendar } from '../assets/img/icons/hr-calendar.svg';
export { default as hr_timeOffTypes } from '../assets/img/icons/permission-01.svg';
export { default as hr_timeOffProfile } from '../assets/img/icons/permission-02.svg';
export { default as hr_permision } from '../assets/img/icons/permission-03.svg';
export { default as permission_04 } from '../assets/img/icons/permission-04.svg';
export { default as permission_05 } from '../assets/img/icons/permission-05.svg';
export { default as permission_06 } from '../assets/img/icons/permission-06.svg';
export { default as permission_07 } from '../assets/img/icons/permission-07.svg';
export { default as permission_08 } from '../assets/img/icons/permission-08.svg';
export { default as permission_09 } from '../assets/img/icons/permission-09.svg';
export { default as permission_10 } from '../assets/img/icons/permission-10.svg';
export { default as permission_11 } from '../assets/img/icons/permission-11.svg';
export { default as permission_12 } from '../assets/img/icons/permission-12.svg';

export { default as permission_13 } from '../assets/img/icons/permission-13.svg';
export { default as permission_14 } from '../assets/img/icons/permission-14.svg';
export { default as permission_15 } from '../assets/img/icons/permission-15.svg';
export { default as permission_16 } from '../assets/img/icons/permission-16.svg';
export { default as permission_17 } from '../assets/img/icons/permission-17.svg';
export { default as permission_18 } from '../assets/img/icons/permission-18.svg';
export { default as permission_19 } from '../assets/img/icons/permission-19.svg';
export { default as permission_20 } from '../assets/img/icons/permission-20.svg';
export { default as permission_21 } from '../assets/img/icons/permission-21.svg';
export { default as permission_22 } from '../assets/img/icons/permission-22.svg';
export { default as permission_23 } from '../assets/img/icons/permission-23.svg';
export { default as permission_24 } from '../assets/img/icons/permission-24.svg';
export { default as permission_25 } from '../assets/img/icons/permission-25.svg';
export { default as permission_26 } from '../assets/img/icons/permission-26.svg';
export { default as permission_27 } from '../assets/img/icons/permission-27.svg';
export { default as permission_28 } from '../assets/img/icons/permission-28.svg';
export { default as permission_29 } from '../assets/img/icons/permission-29.svg';
export { default as permission_30 } from '../assets/img/icons/permission-30.svg';

export { default as permissionEye } from '../assets/img/icons/permission-eye.svg';
export { default as permissionLock } from '../assets/img/icons/permission-lock.svg';
export { default as permissionPencil } from '../assets/img/icons/permission-pencil.svg';
export { default as permissionUnLock } from '../assets/img/icons/permission-unlock.svg';

export { default as darkLocation } from '../assets/img/icons/dark-location-icon.svg';

export { default as timeOff_1 } from '../assets/img/icons/time-off-01.svg';
export { default as timeOff_2 } from '../assets/img/icons/time-off-02.svg';
export { default as publicHoliday } from '../assets/img/icons/public_holiday.svg';
export { default as timeOff_3 } from '../assets/img/icons/time-off-03.svg';
export { default as timeOff_4 } from '../assets/img/icons/time-off-04.svg';
export { default as compassion } from '../assets/img/icons/compassion-icon.svg';
export { default as child_icon } from '../assets/img/icons/child-icon.svg';
export { default as training_icon } from '../assets/img/icons/training-icon.svg';
export { default as jury } from '../assets/img/icons/jury.svg';
export { default as hrRequest } from '../assets/img/icons/hr-request.svg';
export { default as Notification_2 } from '../assets/img/icons/hr-notification.svg';
export { default as Notification_Calender } from '../assets/img/icons/hr-noti-calender.svg';
export { default as Notification_Topic } from '../assets/img/icons/notification-topic.svg';

export { default as menuDots } from '../assets/img/icons/menu-dots.svg';
export { default as info } from '../assets/img/icons/info_2.svg';
export { default as dashboard_report } from '../assets/img/icons/reports/dashboard.svg';
export { default as desk_report } from '../assets/img/icons/reports/desk.svg';
export { default as engagement_report } from '../assets/img/icons/reports/engagement.svg';
export { default as etc_report } from '../assets/img/icons/reports/etc.svg';
export { default as parking_report } from '../assets/img/icons/reports/parking.svg';
export { default as performance_report } from '../assets/img/icons/reports/performance.svg';
export { default as room_report } from '../assets/img/icons/reports/room.svg';
export { default as shield_report } from '../assets/img/icons/reports/shield.svg';
export { default as visitor_report } from '../assets/img/icons/reports/visitor.svg';
export { default as today_report } from '../assets/img/icons/reports/visitor.svg';

export { default as arrow_forward_ios } from '../assets/img/icons/arrow_forward_ios.svg';
export { default as arrow_backward_ios } from '../assets/img/icons/arrow_backward_ios.svg';
export { default as arrow_forward } from '../assets/img/icons/arrow_forward.svg';
export { default as arrow_backward } from '../assets/img/icons/arrow_backward.svg';
export { default as tabIcon4 } from '../assets/img/icons/tab-icon4.svg';
export { default as tabIcon5 } from '../assets/img/icons/tab-icon5.svg';
export { default as orgEdit } from '../assets/img/icons/org-pencil.svg';
export { default as hrLocationIcon } from '../assets/img/icons/hr-location-icon.svg';
export { default as deskRedIcon } from '../assets/img/icons/desk-red1.svg';

export {default as team_report} from '../assets/img/icons/team-reporting-icon.svg';
export {default as av1} from '../assets/img/icons/avatar.png';
export {default as newJoiners} from '../assets/img/icons/newJoiners.png';
export {default as leavers} from '../assets/img/icons/leavers.png';
export {default as withoutpayrise} from '../assets/img/icons/withoutpayrise.png';
export {default as birthday} from '../assets/img/icons/Birthday.svg';
export {default as workanniversary} from '../assets/img/icons/workAnniversary.png';
export {default as timeoffreq} from '../assets/img/icons/timeoffreq.png';
export {default as homeRemote} from '../assets/img/icons/VectorRemote.png';
export {default as carbon_unknown} from '../assets/img/icons/carbon_unknown.svg';
export { default as client_site } from '../assets/img/icons/client_site.svg'; 

