export const TeamListLabel = {
  Team_manager: 'Team_manager',
  TeamManager: 'Team manager',
  Summary: 'Summary',
  Team: 'Team',
  Teams: 'Teams',
  Return_to_team: 'Return_to_team',
  Returntoteam: 'Return to team',
  View_team: 'View_team',
  Viewteam: 'View team',
  About: 'About',
  Location: 'Location',
  Default_working_hours: 'Default_working_hours',
  Defaultworkinghours: 'Default working hours',
  Start: 'Start',
  End: 'End',
  Contact: 'Contact',
};
